package Event;

public enum EventType {
    ALARM,
    ALARM_CLOCK_ARMED,
    ALARM_CLOCK_REMOVED,
    REQUEST_ADD_ALARM_CLOCK,
    REQUEST_REMOVE_ALARM_CLOCK,
    REQUEST_START,
    REQUEST_PAUSE,
    REQUEST_RESET,
    REQUEST_TIME_UPDATE,
    TIME_UPDATE,
}
